config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

  resources :kittens

end

app/models/kitten.rb
# == Schema Information
#
# Table name: kittens
#
#  id         :integer          not null, primary key
#  name       :string
#  age        :integer
#  cuteness   :string
#  softness   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if(@kitten.save!)
      redirect_to @kitten
    else
      render :new
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update!(kitten_params)
      redirect_to @kitten
    else
      render :edit
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    Kitten.find(params[:id]).destroy
    redirect_to root_path
  end

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.haml
= simple_form_for @kitten do |f|
  = f.input :name, label: "Name of Kitteh: "
  = f.input :age, label: "Age in years: "
  = f.input :cuteness, label: "How cute? "
  = f.input :softness, label: "How soft? "
  = f.button :submit

app/views/kittens/edit.html.haml
%h1 Editing a kittehh
= render 'form'

app/views/kittens/index.html.haml
%h1 All of da kittays!
= link_to "Create your own lil kittehh!", new_kitten_path
- @kittens.each do |kitten|
  %li= link_to "#{kitten.name}", kitten

app/views/kittens/new.html.haml
%h1 Create a new Kittehh
= render 'form'

app/views/kittens/show.html.haml
%h1= "Profile of #{@kitten.name}"
%p= "I am #{pluralize(@kitten.age, 'year')} old."
%p= "I am #{@kitten.cuteness} cute, and #{@kitten.softness} soft!"
= link_to "edit", edit_kitten_path
= link_to "delete", @kitten, method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KittensApi
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield